### ISSUE TITLE
Citing?

### ISSUE THREAD

**Issue by kindofausername** [dandewaters/VCF-File-Converter#2]
How do you want me to cite your script?

Greetings
Armin

**Comment by dandewaters** [comment]
I would recommend using the updated version of this code and citing that, I only kept this repository up for papers that have previously cited my code. But if you prefer to use this code, here's a citation in CSE Bibliography Format:
 
DeWaters, D. 2018. VCF File Converter. Waldorf (MD): GitHub; [accessed Year Month Day]. https://github.com/dandewaters/VCF-File-Converter.
